### ISSUE TITLE
How to use this repository?

### ISSUE THREAD

**Issue by KurtSunxx** [zhoumingyi/DaST#1]
Sir, Can you tell me how to use this repository? @zhoumingyi

**Comment by Alamnoor** [comment]
We would be thankful if you will give complete detail of training process and dependency? Please comment if possible. Thanks

**Comment by hujipeng666666** [comment]
Traceback (most recent call last):
  File "D:/DaST-master/dast.py", line 82, in <module>
    clf = joblib.load('pretrained/sklearn_mnist_model.pkl')
  File "D:\anaconda2\envs\pytorch-gpu\lib\site-packages\sklearn\externals\joblib\numpy_pickle.py", line 570, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'pretrained/sklearn_mnist_model.pkl'

请问这个错误该如何解决呢？

**Comment by KurtSunxx** [comment]
我不知道，我看到没有说怎么使用这个代码，我就没有用过了


 
---Original---

**Comment by KurtSunxx** [comment]
Sorry sir,&nbsp; I do not use this repo until now


 
---Original---

**Comment by hujipeng666666** [comment]
> 我不知道，我看到没有说怎么使用这个代码，我就没有用过了
> […](#)
> ---原始版本---来自：“ hujipeng666666” <notifications@github.com> 日期：2020/7/25 16:30:26收件人：“ zhoumingyi / DaST” <DaST@noreply.github.com> ;; 抄送：“作者” <author@noreply.github.com> ;;“许向阳” <1137582789@qq.com> 主题：回复：[zhoumingyi / DaST]如何使用此存储库？（[＃1](https://github.com/zhoumingyi/DaST/issues/1)）追溯（最近一次通话最后一次）：文件“ D：/DaST-master/dast.py”，第82行，在clf = joblib.load（'pretrained / sklearn_mnist_model.pkl'）文件“ D：\ anaconda2 \ envs \ pytorch-gpu \ lib \ site-packages \ sklearn \ externals \ joblib \ numpy_pickle.py“，第570行，在加载时以open（filename，'rb'）的形式显示为f：FileNotFoundError：[Errno 2]没有此类文件或目录：“ pretrained / sklearn_mnist_model.pkl” 请问这个错误该如何解决呢？—您收到此消息是因为您编写了该线程。直接回复此电子邮件，在GitHub上查看或取消订阅。

好的，谢谢同学，如果你打算运行这个代码的话，我们可以一起交流一下。握手。

**Comment by zhoumingyi** [comment]
Sorry, I just finished my graduation trip, I will add an introduction to the readme and solve the bugs.

**Comment by zhoumingyi** [comment]
I have added some notes in the readme file. If you have any problems in your own dataset, you can upload your code and I will help you to address it.

**Comment by KurtSunxx** [comment]
Fine. Congratulations firstly. Waiting for it! 1137582789 Email:1137582789@qq.com Signature is customized by Netease Mail Master On 07/27/2020 11:24, Mingyi Zhou wrote: Sorry, I just finished my graduation trip, I will add an introduction to the readme and solve the bugs. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
