### ISSUE TITLE
关于scikit-learn版本问题

### ISSUE THREAD

**Issue by 1392081456** [zhoumingyi/DaST#13]
作者您好，在复现您论文中关于 Microsoft Azure example model模型的时候 ，出现了ModuleNotFoundError: No module named 'sklearn.linear_model.logistic'的错误， 经查询可能是scikit-learn的版本问题，我的版本是1.2.2，请问作者您的版本是多少呢？

**Comment by zhoumingyi** [comment]
I am sorry to reply late. I forgot the version of scikit-learn when I uploaded the codes. But I remember I had this problem before, you could try to downgrade the scikit-learn. I haven't had a chance to use it recently, I am sorry that I cannot provide a valid solution.

**Comment by 1392081456** [comment]
> I am sorry to reply late. I forgot the version of scikit-learn when I uploaded the codes. But I remember I had this problem before, you could try to downgrade the scikit-learn. I haven't had a chance to use it recently, I am sorry that I cannot provide a valid solution.
十分感谢你在百忙之中回复这个问题，我已经解决了这个问题，复现Microsoft Azure example model的版本是scikit-learn是0.21.3。希望这个回答也能够为后来想复现这个实验的人一点帮助。

Thank you very much for taking the time to reply to this question. I have solved this problem. The version to reproduce the Microsoft Azure example model is scikit-learn 0.21.3. I hope this answer can also be of some help to those who want to reproduce this experiment later.

**Comment by 1392081456** [comment]
> I am sorry to reply late. I forgot the version of scikit-learn when I uploaded the codes. But I remember I had this problem before, you could try to downgrade the scikit-learn. I haven't had a chance to use it recently, I am sorry that I cannot provide a valid solution.

十分感谢你在百忙之中回复这个问题，我已经解决了这个问题，复现Microsoft Azure example model的版本是scikit-learn是0.21.3。希望这个回答也能够为后来想复现这个实验的人一点帮助。

**Comment by 1392081456** [comment]
> I am sorry to reply late. I forgot the version of scikit-learn when I uploaded the codes. But I remember I had this problem before, you could try to downgrade the scikit-learn. I haven't had a chance to use it recently, I am sorry that I cannot provide a valid solution.

十分感谢你在百忙之中回复这个问题，我已经解决了这个问题，复现Microsoft Azure example model的版本是scikit-learn是0.21.3。希望这个回答也能够为后来想复现这个实验的人一点帮助。

Thank you very much for taking the time to reply to this question. I have solved this problem. The version to reproduce the Microsoft Azure example model is scikit-learn 0.21.3. I hope this answer can also be of some help to those who want to reproduce this experiment later.
