### ISSUE TITLE
对于源码复现的疑问

### ISSUE THREAD

**Issue by hujipeng666666** [zhoumingyi/DaST#3]
请问这个sklearn_mnist_model.pkl
![捕获](https://user-images.githubusercontent.com/39931365/88458961-23ef0400-cec4-11ea-9ad0-e9428a1d2aab.JPG)
文件，为啥pretrained文件夹里没有呢？这样的话会一直报错的

**Comment by zhoumingyi** [comment]
I have added it, you can check it again.

**Comment by hujipeng666666** [comment]
> 我已添加它，您可以再次检查。

好的好的，非常感谢！
