### ISSUE TITLE
麻烦帮忙看一下，这个存模型为什么会报错呢

### ISSUE THREAD

**Issue by hujipeng666666** [zhoumingyi/DaST#4]
FileNotFoundError                         Traceback (most recent call last)
~/DaST-master/dast.py in <module>
    479     if best_att < (total - correct_ghost):
    480         torch.save(netD.state_dict(),
--> 481                     opt.save_folder + '/netD_epoch_%d.pth' % (epoch))
    482         torch.save(netG.state_dict(),
    483                     opt.save_folder + '/netG_epoch_%d.pth' % (epoch))

/usr/local/lib/python3.6/dist-packages/torch/serialization.py in save(obj, f, pickle_module, pickle_protocol, _use_new_zipfile_serialization)
    367             return
    368 
--> 369     with _open_file_like(f, 'wb') as opened_file:
    370         _legacy_save(obj, opened_file, pickle_module, pickle_protocol)
    371 

/usr/local/lib/python3.6/dist-packages/torch/serialization.py in _open_file_like(name_or_buffer, mode)
    232 def _open_file_like(name_or_buffer, mode):
    233     if _is_path(name_or_buffer):
--> 234         return _open_file(name_or_buffer, mode)
    235     else:
    236         if 'w' in mode:

/usr/local/lib/python3.6/dist-packages/torch/serialization.py in __init__(self, name, mode)
    213 class _open_file(_opener):
    214     def __init__(self, name, mode):
--> 215         super(_open_file, self).__init__(open(name, mode))
    216 
    217     def __exit__(self, *args):

FileNotFoundError: [Errno 2] No such file or directory: 'saved_model/netD_epoch_0.pth'

Attack success rate: 48.20 %

**Comment by hujipeng666666** [comment]
![image](https://user-images.githubusercontent.com/39931365/89103507-f4e90d00-d444-11ea-9527-4e143d40f227.png)
保存模型出错可能是这个原因，请问您用的pytorch是什么版本呢？

**Comment by hujipeng666666** [comment]
> FileNotFoundError Traceback (most recent call last)
> ~/DaST-master/dast.py in
> 479 if best_att < (total - correct_ghost):
> 480 torch.save(netD.state_dict(),
> --> 481 opt.save_folder + '/netD_epoch_%d.pth' % (epoch))
> 482 torch.save(netG.state_dict(),
> 483 opt.save_folder + '/netG_epoch_%d.pth' % (epoch))
> 
> /usr/local/lib/python3.6/dist-packages/torch/serialization.py in save(obj, f, pickle_module, pickle_protocol, _use_new_zipfile_serialization)
> 367 return
> 368
> --> 369 with _open_file_like(f, 'wb') as opened_file:
> 370 _legacy_save(obj, opened_file, pickle_module, pickle_protocol)
> 371
> 
> /usr/local/lib/python3.6/dist-packages/torch/serialization.py in _open_file_like(name_or_buffer, mode)
> 232 def _open_file_like(name_or_buffer, mode):
> 233 if _is_path(name_or_buffer):
> --> 234 return _open_file(name_or_buffer, mode)
> 235 else:
> 236 if 'w' in mode:
> 
> /usr/local/lib/python3.6/dist-packages/torch/serialization.py in **init**(self, name, mode)
> 213 class _open_file(_opener):
> 214 def **init**(self, name, mode):
> --> 215 super(_open_file, self).**init**(open(name, mode))
> 216
> 217 def **exit**(self, *args):
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'saved_model/netD_epoch_0.pth'
> 
> Attack success rate: 48.20 %
我手动创建了一个saved_model文件夹，问题解决。

**Comment by zhoumingyi** [comment]
Sorry, I have added the saved_model folder.
