### ISSUE TITLE
关于evalution的问题

### ISSUE THREAD

**Issue by hujipeng666666** [zhoumingyi/DaST#5]
![image](https://user-images.githubusercontent.com/39931365/89105439-b3ac2980-d453-11ea-8109-7831b3fe1f5d.png)
![image](https://user-images.githubusercontent.com/39931365/89105457-d6d6d900-d453-11ea-93ad-cc52211ffb8c.png)
为什么总是显示未定义呢

**Comment by zhoumingyi** [comment]
你需要在运行evaluate.py的时候用--attack_net参数制定一下，抱歉这个地方我没注释该怎么用这个文件，我明天在readme中详细说一下

**Comment by hujipeng666666** [comment]
好的，非常感谢。

**Comment by zhoumingyi** [comment]
我发现evaluation文件里有一些问题，训练和测试不匹配，重写了其中一部分
