### ISSUE TITLE
关于loss的疑问

### ISSUE THREAD

**Issue by hujipeng666666** [zhoumingyi/DaST#6]
你好，请问一下这个论文中的loss和代码中实现的loss函数为啥有点不一样呢？论文中在e的多少次方上好像没有包含标签损失函数。
![image](https://user-images.githubusercontent.com/39931365/89125052-40b3b900-d50e-11ea-87fe-c548d1f594cb.png)
![image](https://user-images.githubusercontent.com/39931365/89125116-b1f36c00-d50e-11ea-980c-07c1a2dfbfc2.png)

**Comment by zhoumingyi** [comment]
论文中这个d指的是T和D输出间的距离，如果在DaST-L模式下，攻击者只能获得T的输出标签值，所以d值得是标签间的差异，所以用了交叉熵loss。如果在DaST-P模式下，攻击者能获得概率值，所以这个d代表的距离值不仅可以有标签间的差异，也可以有概率值间的差异。总而言之，d是一种泛指，代表T、D间的输出差异，可以由多种计算方法来表示，也可以用我的代码之外的计算方法。

**Comment by hujipeng666666** [comment]
等于说下面这个代码实现的loss是将标签差异加上标签概率差异，这样理解对吗
![image](https://user-images.githubusercontent.com/39931365/89126218-9ab87c80-d516-11ea-99b9-6b4a104b8810.png)

**Comment by zhoumingyi** [comment]
对的，因为在攻击者能获取概率值的情况下，也能直接算出最后label了。所以在实际应用中，攻击者是可以两种距离搭配使用，而且我发现实验中这样效果也会更好。

**Comment by hujipeng666666** [comment]
好的，理解了，感谢。还想问下论文中下面这个生成器的总loss在这个代码中有实现吗？还是说代码中使用了另一种计算方法实现？
![image](https://user-images.githubusercontent.com/39931365/89126237-d3585600-d516-11ea-9865-174636f8c610.png)

**Comment by zhoumingyi** [comment]
有实现的在436-438的
```python
        loss_imitate = criterion_max(pred=output, truth=label, proba=outputs)
        loss_diversity = criterion(output, set_label.squeeze().long())
        errG = opt.alpha * loss_diversity + loss_imitate
```

**Comment by hujipeng666666** [comment]
感谢，理解了。还有一个问题就是
![image](https://user-images.githubusercontent.com/39931365/89157228-bebfa080-d59e-11ea-8038-c79804f234c6.png)

论文中的两个n和代码实现的这个都是代表某一个标签类别吗，那怎么保证使用这个标签控制损失涵盖所有的类别呢

**Comment by zhoumingyi** [comment]
n是随机采样的，假如有10个类别，那就从0-10中随机采样。这个loss就是约束G输出的样本在T的分类下能够为我们预设好的类别n。在训练过程良好时，由于n随机采样包含所有类别，G的输出也会包含所有类别。

**Comment by hujipeng666666** [comment]
> n是随机采样的，假如有10个类别，那就从0-10中随机采样。这个loss就是约束G输出的样本在T的分类下能够为我们预设好的类别n。在训练过程良好时，由于n随机采样包含所有类别，G的输出也会包含所有类别。

好的懂了，非常感谢耐心答复。
